name: FirmAI
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 2..3
incremental: true
permalink: pretty
safe: false
lsi: false
url: https://firmai.com
keep_files: ["v17.06"]

plugins_dir:
  - jekyll-sitemap
  - jekyll-target-blank
# Component versions -- address like site.docker_ce_stable_version
# You can't have - characters in these for non-YAML reasons

docker_ce_stable_version: "17.09"


ucp_versions:
  - version: "2.2"
    latest: true
    path: /datacenter/ucp/2.2/guides/
  - version: "2.1"
    path: /datacenter/ucp/2.1/guides/
  - version: "2.0"
    path: /datacenter/ucp/2.0/guides/
  - version: "1.1"
    path: /datacenter/ucp/1.1/overview/

dtr_versions:
  - version: "2.4"
    path: /datacenter/dtr/2.4/guides/
    latest: true
  - version: "2.3"
    path: /datacenter/dtr/2.3/guides/
  - version: "2.2"
    path: /datacenter/dtr/2.2/guides/
  - version: "2.1"
    path: /datacenter/dtr/2.1/guides/
  - version: "2.0"
    path: /datacenter/dtr/2.0/

tablabels:
  ucp-3.0: Universal Control Plane 3.0
  ucp-2.2: Universal Control Plane 2.2
  docker-cli-linux: Docker CLI on Mac/Linux
  docker-cli-win: Docker CLI on Windows
  kubectl: Kubernetes CLI

collections:
  samples:
    output: true

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-relative-links

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      defaultassignee: firmai
      toc_min: 2
      toc_max: 3
      tree: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

theme: jekyll-theme-cayman